### ISSUE TITLE
It gives sound nullsafety error

### ISSUE THREAD

**Issue by latestbob** [Flutterwave/flutterwave-flutter#55]
The package still gives sound null safety error

**Comment by juniorkibirige** [comment]
Will be solved once PR:#48 has been appended into the main branch

**Comment by blackmann** [comment]
Hello @juniorkibirige, tried your PR, but I get some "encryption" errors... (sorry, I couldn't make a screen grab - but it was along the lines of "check if your encryption matches blah blah")

**Comment by blackmann** [comment]
@latestbob if urgent you can use this commit which makes use of a null safe [`tripledes` PR#14](https://github.com/johnpryan/tripledes-dart/pull/14). Replace your flutter wave package with this in `pubspec.yaml`

```yaml
  flutterwave:
    git:
      url: https://github.com/blackmann/flutterwave-flutter.git
      ref: development
```

Note: this is not an official solution
